In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import linalg, sparse

In [22]:
l = list(range(10))
print (type(l))

v = np.array(l)
print(type(v))
v.shape

<class 'list'>
<class 'numpy.ndarray'>


(10,)

In [12]:
v = np.matrix(zip(range(5), range(5,10)))
v



matrix([[<zip object at 0x000000000AF8F7C8>]], dtype=object)

In [21]:
M = np.matrix([[3,4, 5], [5,6, 7]])
print(M.shape)
M



(2, 3)


matrix([[3, 4, 5],
        [5, 6, 7]])

#### Creating matrices

In [50]:
shape_2d = (3,2) # 3 rows by 2 columns
print(np.ones(shape_2d))    # Create an array of ones
print(np.empty(shape_2d))   # Create an empty array
print(np.zeros(shape_2d))   # Create an array of zeros
print(np.full(shape_2d, 7, dtype=np.int32))  # Create an array filled with value
print(np.random.random((2,2))) # Create an array with random values

# 3-dimensional arrays
shape_3d = (2,3,4)
np.zeros(shape_3d,dtype=np.int16)

# Ranges of values 
print(np.arange(10, 25,5)) # Array of values from 10 to 25 with 5 increment
print(np.linspace(0,2,9))  #Array of values from 0 to 2 with 9 elements


# Identity matrix
np.identity(4)
np.eye(4)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[7 7]
 [7 7]
 [7 7]]
[[ 0.73067266  0.05684699]
 [ 0.34235785  0.42729677]]
[10 15 20]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

#### Matrix operations

* The addition is the pointwise sum of the elements in the corresponding positions.
* The scalar multiplication is performed by multiplying every element of the matrix with the scalar.

In [55]:
A = np.array([[1,0],
              [2,5],
              [3,1]])
B = np.array([[4,0.5],
              [2,5],
              [0,1]])
print(A + B)
print(3 * A)

[[  5.    0.5]
 [  4.   10. ]
 [  3.    2. ]]
[[ 3  0]
 [ 6 15]
 [ 9  3]]


* Matrix multiplication **is not** commutative in general, i.e. $$A \times B \neq B \times A$$
* Matrix multiplication **is** associative, i.e. $$ A \times (B \times C) = (A \times B) \times C$$

* **Inverse** If $A$ is an $m \times m$ (square) matrix, and if it has an inverse, then $$A (A^{-1}) = A^{-1} A = I $$
Not all matrices have inverses, and the intuition is that those matrices are too close to zero (similar to computing the inverse of a scalar, e.g. the inverse of 3 is 1/3, but the inverse of 0 doesn't exist). The matrices that don't have an inverse are called "singular" or "degenerate"

* **Transpose** LEt $A$ be an $m \times n$ matrix and let $B = A^T$. Then $B$ is a $n \times m$ matrix such that $B_{ij} = A_{ji}$